package com.psit.Dto;

import java.time.LocalDateTime;

import javax.persistence.Column;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;


@Setter
@Getter
@ToString
public class EmployeeDto {
	
	//employeeDto will contains all the variable except id, isactive,created date and updated date
	//id will be autogenerated and  isactive,created date and updated date we will set manualy while converting dto into entity in servuce class
	private String firstName;

	private String lastName;
	private String email;
    private Long mobileNo;
	private Double salary;
    private LocalDateTime dateOfJoining;
}
